Add js tests.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,9 +6,6 @@
 # Author: Jean Valverde contact@dev-drupal.com
 # License: GPL-3
 #
-# This file is way too huge for a normal CI process, this is just a commented
-# example of working jobs for Drupal 8, feel free to cherry pick what you need.
-#
 # For Gilab CI help on this file see:
 #   https://docs.gitlab.com/ee/ci/yaml
 #
@@ -44,8 +41,8 @@ variables:
   PHP_CODE: "${WEB_ROOT}/modules/contrib,${WEB_ROOT}/themes/contrib"
   # Space separated for eslint and sass lint.
   JS_CODE: "${WEB_ROOT}/modules/contrib/**/*.js ${WEB_ROOT}/themes/contrib/**/*.js"
-  CSS_FILES: "${WEB_ROOT}/themes/contrib/**/css/*.css"
-  SCSS_FILES: "${WEB_ROOT}/themes/contrib/**/scss/*.scss"
+  CSS_FILES: "${WEB_ROOT}/themes/contrib/**/css/*.css ${WEB_ROOT}/themes/custom/**/css/**/*.css"
+  SCSS_FILES: "${WEB_ROOT}/themes/contrib/**/scss/*.scss ${WEB_ROOT}/themes/custom/**/scss/**/*.scss"
   SASS_CONFIG: "./.sass-lint.yml"
   # Ignore files and dir for all Phpqa tools.
   PHPQA_IGNORE_DIRS: "--ignoredDirs vendor,bootstrap,tests"
@@ -103,6 +100,7 @@ before_script:
 
 # Testing template for phpunit, this provide Apache / Php.
 .test_template: &test_template
+  # Because some contrib tests failed, keep it informative.
   allow_failure: true
   # Build is not for master but only branch testing or tags for release.
   # Limit to branch push, for more options see
@@ -129,15 +127,21 @@ before_script:
     - chmod -R g+s "${BROWSERTEST_OUTPUT_DIRECTORY}"
     - chown -R www-data:www-data ${WEB_ROOT}
     - apache2-foreground&
-    # Import dump from cache if available, or Setup Drupal.
+    # Import dump from cache if available, or Install Drupal.
     - mkdir -p dump && chmod -R 777 dump
-    - if [ -f "${DB_DUMP}" ];
+    - if [ "${INSTALL_DRUPAL}" == "1" ];
       then
-        mysql -hmariadb -uroot drupal < ${CI_PROJECT_DIR}/${DB_DUMP};
-      else
-        robo setup:drupal;
+        if [ -f "${DB_DUMP}" ];
+        then
+          mysql -hmariadb -uroot drupal < ${CI_PROJECT_DIR}/${DB_DUMP};
+        else
+          robo setup:drupal;
+        fi
       fi
-    - robo check:drupal
+    - if [ "${INSTALL_DRUPAL}" == "1" ];
+      then
+        robo check:drupal;
+      fi
   variables:
     MYSQL_ALLOW_EMPTY_PASSWORD: "1"
     MYSQL_DATABASE: "drupal"
@@ -145,6 +149,8 @@ before_script:
     SIMPLETEST_BASE_URL: "http://localhost"
     SIMPLETEST_DB: "mysql://root@mariadb/drupal"
     BROWSERTEST_OUTPUT_DIRECTORY: "/var/www/html/web/sites/simpletest"
+    # Install Drupal flag
+    INSTALL_DRUPAL: "1"
     # Install Drupal from config in ./config/sync with config_installer.
     SETUP_FROM_CONFIG: "1"
   artifacts:
@@ -183,7 +189,14 @@ Build:
   #  - testing
   #  - tags
   script:
-    # Check composer first, then install.
+  script:
+    # [COMPOSER.JSON]
+    # Download Drupal project when no composer.json.
+    # - robo download:drupal-project
+    # Because create-project need an empty folder we copy the downloaded drupal.
+    # - cp -rf drupal/* ${CI_PROJECT_DIR} && cp -f drupal/.e* ${CI_PROJECT_DIR} && cp -f drupal/.g* ${CI_PROJECT_DIR} || true
+    #
+    # Check composer.json file first, then install.
     - composer --verbose --no-check-all --no-check-publish validate
     - robo install:drupal
   # On build we cache the composer, web folders.
@@ -201,7 +214,7 @@ Build:
       - scripts
       - composer.json
       - composer.lock
-      # Specific to drupal-composer/drupal-project.
+      # [COMPOSER.JSON]  Specific to drupal-composer/drupal-project.
       - .env.example
       - load.environment.php
     expire_in: 1 day
@@ -222,6 +235,7 @@ Security report:
       fi
   dependencies:
     - Build
+  # Because some contrib tests failed, keep it informative.
   allow_failure: true
 
 # Job to run Unit and Kernel tests.
@@ -257,34 +271,60 @@ Functional:
   dependencies:
     - Build
 
+# https://cgit.drupalcode.org/drupal/tree/core/tests/README.md
+Functional Js:
+  image: mogtofu33/drupal8ci:8.6-selenium-no-drupal
+  stage: tests
+  <<: *test_template
+  services:
+    - mariadb:latest
+  script:
+    - /scripts/start-selenium-standalone.sh&
+    - sleep 5s
+    # Test selenium is running.
+    - test=$(curl -s http://localhost:4444/wd/hub/status | jq '.status'); if ! [ $__test=0 ]; then exit 1; fi
+    - curl -s http://localhost:4444/wd/hub/status | jq '.'
+    - robo test:suite "${TESTS}functional-javascript" "${REPORT_DIR}"
+  dependencies:
+    - Build
+  variables:
+    MYSQL_ALLOW_EMPTY_PASSWORD: "1"
+    MYSQL_DATABASE: "drupal"
+    DB_DUMP: "dump/dump.sql"
+    SIMPLETEST_BASE_URL: "http://localhost"
+    SIMPLETEST_DB: "mysql://root@mariadb/drupal"
+    BROWSERTEST_OUTPUT_DIRECTORY: "/var/www/html/web/sites/simpletest"
+    MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless","--no-sandbox","--window-size=1920,1080"]}}, "http://localhost:4444/wd/hub"]'
+    APACHE_RUN_USER: "www-data"
+    APACHE_RUN_GROUP: "www-data"
+
 # Job to run Functional Javascript tests with Nightwatch.
 # https://www.drupal.org/docs/8/testing/javascript-testing-using-nightwatch
 # https://cgit.drupalcode.org/drupal/tree/core/tests/README.md
 Nightwatch Js:
+  image: mogtofu33/drupal8ci:8.6-selenium-no-drupal
   stage: tests
   <<: *test_template
   dependencies:
     - Build
   services:
     - mariadb:latest
-    - name: selenium/standalone-chrome:latest
-      alias: chromedriver
   script:
-    # Test selenium is sup.
-    #- test=$(curl -s http://chromedriver:4444/wd/hub/status | jq '.status'); if ! [ $__test=0 ]; then exit 1; fi
-    #- curl -s http://chromedriver:4444/wd/hub/status | jq '.'
-    - cp .gitlab-ci/.env.chrome ${WEB_ROOT}/core/.env || true
-    - cd ${WEB_ROOT}/core
+    - cp .gitlab-ci/.env.ci ${WEB_ROOT}/core/.env || true
+    # Patch for Nightwatch to allow install profile.
+    - cd ${WEB_ROOT}
+    - curl -fsSL https://www.drupal.org/files/issues/2019-02-05/3017176-7.patch -o 3017176-7.patch
+    - patch -p1 < 3017176-7.patch || true
+    - cd core
     - yarn install
-    - yarn test:nightwatch --tag custom
+    # - yarn test:nightwatch --tag ${TESTS} --verbose
+    - yarn test:nightwatch --tag ${TESTS}
   variables:
     MYSQL_ALLOW_EMPTY_PASSWORD: "1"
     MYSQL_DATABASE: "drupal"
     BROWSERTEST_OUTPUT_DIRECTORY: "/var/www/html/web/sites/simpletest"
-    DOCKER_HOST: tcp://docker:2375
-    DOCKER_DRIVER: overlay2
-  # Because current core tests failed.
-  allow_failure: true
+    # No need to pre-install Drupal.
+    INSTALL_DRUPAL: "0"
 
 ################################################################################
 # Code quality jobs for Drupal 8+
@@ -303,6 +343,7 @@ Code quality:
     <<: *default_artifacts
   script:
     - phpqa ${PHPQA_REPORT} ${TOOLS} ${PHPQA_PHP_CODE}
+  # Because some contrib tests failed, keep it informative.
   allow_failure: true
 
 # Drupal coding standard best practices report.
