Update CI.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -52,6 +52,7 @@ stages:
   only:
     refs:
       - 8.x-dev
+      - testing
       - tags
 
 # Reports produced and visible in job report.
@@ -80,7 +81,7 @@ stages:
   SIMPLETEST_DB: "mysql://root@mariadb/drupal"
   BROWSERTEST_OUTPUT_DIRECTORY: "${WEB_ROOT}/sites/simpletest"
   # No spaces.
-  MINK_DRIVER_ARGS_WEBDRIVER: '["chrome",{"browserName":"chrome","chromeOptions":{"args":["--whitelisted-ips","--disable-gpu","--headless","--no-sandbox","--window-size=1920,1080"]}},"http://localhost:4444/wd/hub"]'
+  MINK_DRIVER_ARGS_WEBDRIVER: '["chrome",{"browserName":"chrome","chromeOptions":{"w3c":false,"args":["--whitelisted-ips","--disable-gpu","--headless","--no-sandbox","--window-size=1920,1080"]}},"http://localhost:4444/wd/hub"]'
   APACHE_RUN_USER: "www-data"
   APACHE_RUN_GROUP: "www-data"
   # Selenium extra options, see
@@ -106,12 +107,11 @@ stages:
     - apache2-foreground&
     # Copy files and prepare test folder with permissions.
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/phpunit.xml ${WEB_ROOT}/core || true
-    - mkdir -p "${BROWSERTEST_OUTPUT_DIRECTORY}/browser_output"
-    - chmod -R g+s "${BROWSERTEST_OUTPUT_DIRECTORY}"
-    - chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} ${BROWSERTEST_OUTPUT_DIRECTORY}
-    - chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} ${WEB_ROOT}/sites
-    - mkdir -p "${REPORT_DIR}"
-    - chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} ${REPORT_DIR}
+    # Allow phpunit.xml override
+    - if [ -f ${CI_PROJECT_DIR}/.gitlab-ci/phpunit.xml.dist ]; then
+        cp ${CI_PROJECT_DIR}/.gitlab-ci/phpunit.xml.dist ${WEB_ROOT}/core/phpunit.xml || true;
+      fi
+    - robo ensure:tests-folders
   artifacts:
     <<: *default_artifacts
     paths:
@@ -131,8 +131,12 @@ Build:
   extends: .test_except_only
   script:
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/RoboFile.php ${CI_PROJECT_DIR} || true
-    # check Drupal codebase and composer install if needed.
-    - robo perform:build
+    # Check Drupal codebase and run 'composer install' for a project.
+    - robo project:build
+    # After Drupal install we install core/package.json.
+    - robo yarn:install
+    # Install specific CI tools.
+    - robo install:ci
     # Add here any custom build step, composer run-script, grunt, webpack, yarn...
   variables:
     <<: *test_variables
@@ -146,11 +150,13 @@ Build:
     paths:
       - vendor
       - web
+      - core/node_modules
   artifacts:
     paths:
       # Build files for next steps and deploy/release.
       - vendor
       - web
+      - core/node_modules
       - drush
       - scripts
       - composer.json
@@ -234,26 +240,18 @@ Nightwatch Js:
       - $SKIP_TEST_NIGHTWATCH == "1"
   script:
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/.env.nightwatch ${WEB_ROOT}/core/.env || true
-    # [TEMPORARY] Patch for Nightwatch 1.11+ and allow install profile.
-    - cd ${WEB_ROOT}
-    - curl -fsSL https://www.drupal.org/files/issues/2019-07-02/3059356-12-nightwatch-upgrade.patch -o upgrade.patch
-    - patch -p1 < upgrade.patch || true
-    - curl -fsSL https://www.drupal.org/files/issues/2019-02-05/3017176-7.patch -o 3017176-7.patch
-    - patch -p1 < 3017176-7.patch || true
-    # Regular test commands.
-    - cp ${CI_PROJECT_DIR}/.gitlab-ci/RoboFile.php ${WEB_ROOT} || true
-    - robo prepare:folders
-    - chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} ${WEB_ROOT}/sites
-    - cd ${WEB_ROOT}/core
-    - yarn install
-    # Html reporter.
-    - yarn add nightwatch-html-reporter
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/html-reporter.js ${WEB_ROOT}/core/html-reporter.js || true
-    - mkdir -p ${WEB_ROOT}/core/reports
-    - yarn test:nightwatch ${NIGHTWATCH_TESTS} --reporter ./html-reporter.js
-  after_script:
-    - mkdir -p ${CI_PROJECT_DIR}/${REPORT_DIR}/nightwatch
-    - cp -r ${WEB_ROOT}/core/reports/* ${CI_PROJECT_DIR}/${REPORT_DIR}/nightwatch/
+    # [TEMPORARY] Patch for Nightwatch 1.2+, see https://drupal.org/node/3059356
+    - if [ ${DRUPAL_VERSION} == "8.8" ]; then
+        robo patch:nightwatch https://www.drupal.org/files/issues/2019-08-28/3059356-46.patch;
+      elif [ ${DRUPAL_VERSION} == "8.7" ]; then
+        robo patch:nightwatch ${CI_PROJECT_DIR}/.gitlab-ci/patches/3059356-46_8.7.x_.patch 1;
+      fi
+    # [TEMPORARY] Patch to allow install profile, see https://drupal.org/node/3017176
+    - robo patch:nightwatch https://www.drupal.org/files/issues/2019-02-05/3017176-7.patch
+    - robo yarn:install
+    # This is the main script, 'yarn install' and 'test:nightwatch' from core folder.
+    - robo test:nightwatch
   artifacts:
     <<: *default_artifacts
     paths:
@@ -276,15 +274,18 @@ Security report:
       - $SKIP_TEST_SECURITY == "1"
   before_script:
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/RoboFile.php ${CI_PROJECT_DIR} || true
+    - cp ${CI_PROJECT_DIR}/.gitlab-ci/.phpqa.yml ${CI_PROJECT_DIR}/.phpqa.yml || true
     - robo prepare:folders
   script:
-    - if [ -f composer.lock ]; then
-        security-checker security:check;
-      else
-        echo "[SKIP] No composer.lock file!";
-      fi
+    - phpqa
+        --buildDir ${REPORT_DIR}
+        --tools security-checker:0
+        --analyzedDirs ${DOC_ROOT}
+        --verbose
   dependencies:
     - Build
+  # Allow failure to produce report and warning.
+  allow_failure: true
 
 # Behat tests from tests/ folder.
 Behat tests:
@@ -298,10 +299,10 @@ Behat tests:
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/RoboFile.php ${WEB_ROOT} || true
     - robo prepare:folders
     - robo install:drupal
-    - chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} ${WEB_ROOT}/sites/
     # Starting Chrome, we are not using Selenium.
     - /scripts/start-chrome.sh&
     - sleep 5s && curl -s http://localhost:9222/json/version | jq '.'
+    - robo install:behat
     - robo test:behat "${CI_PROJECT_DIR}/${REPORT_DIR}"
   variables:
     <<: *test_variables
@@ -340,10 +341,10 @@ Pa11y:
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/RoboFile.php ${WEB_ROOT} || true
     - robo prepare:folders
     - robo install:drupal
-    - cd ${WEB_ROOT}/core
-    - cp ${CI_PROJECT_DIR}/.gitlab-ci/pa11y-ci.json ${WEB_ROOT}/core || true
-    - yarn add pa11y-ci
-    - node_modules/.bin/pa11y-ci --config ./pa11y-ci.json
+    # Install Pa11y-ci for tests with yarn.
+    - robo install:pa11y
+    # Run pa11y tests using ./gitlab-ci/pa11y-ci.json file definition.
+    - robo test:pa11y
   after_script:
     - cp -f ${WEB_ROOT}/core/reports/pa11y*.png ${CI_PROJECT_DIR}/${REPORT_DIR}/
   variables:
@@ -352,7 +353,7 @@ Pa11y:
   artifacts:
     <<: *default_artifacts
     paths:
-      - ${REPORT_DIR}/*.png
+      - ${CI_PROJECT_DIR}/*.png
 
 ################################################################################
 # Code quality jobs for Drupal 8+
@@ -383,7 +384,10 @@ Code quality:
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/RoboFile.php ${CI_PROJECT_DIR} || true
     - robo prepare:folders
   script:
-    - phpqa ${PHPQA_REPORT} --tools ${TOOLS} ${PHPQA_PHP_CODE}
+    - phpqa
+        --buildDir ${REPORT_DIR}
+        --tools ${TOOLS}
+        --analyzedDirs ${PHP_CODE}
 
 # Drupal coding standard best practices report.
 Best practices:
@@ -401,7 +405,10 @@ Best practices:
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/RoboFile.php ${CI_PROJECT_DIR} || true
     - robo prepare:folders
   script:
-    - phpqa ${PHPQA_REPORT} --tools ${BEST_PRACTICES} ${PHPQA_PHP_CODE}
+    - phpqa
+        --buildDir ${REPORT_DIR}
+        --tools ${BEST_PRACTICES}
+        --analyzedDirs ${PHP_CODE}
   # Allow failure to produce report and warning.
   allow_failure: true
 
@@ -445,14 +452,11 @@ Js lint:
     # Drupal 8.x specific rules override for passing.
     - curl -fsSL https://git.drupalcode.org/project/drupal/raw/${DRUPAL_VERSION}.x/core/.eslintrc.passing.json
       -o ${WEB_ROOT}/core/.eslintrc.passing.json
+    # Install stylelint from core/package.json
+    - robo yarn:install
   script:
-    # Run the eslint command to generate a report.
-    # Terminal result.
-    - eslint
-        --config ${WEB_ROOT}/core/.eslintrc.passing.json
-        ${JS_CODE}
-    # Html report.
-    - eslint
+    # Run the eslint command to generate an html report.
+    - ${WEB_ROOT}/core/node_modules/.bin/eslint
         --config ${WEB_ROOT}/core/.eslintrc.passing.json
         --format html
         --output-file ${REPORT_DIR}/js-lint-report.html
@@ -477,12 +481,14 @@ Css lint:
     - mkdir -p ${WEB_ROOT}/core
     - curl -fsSL https://git.drupalcode.org/project/drupal/raw/${DRUPAL_VERSION}.x/core/.stylelintrc.json
       -o ${WEB_ROOT}/core/.stylelintrc.json
+    # Install stylelint from core/package.json
+    - robo yarn:install
   script:
-    # Css report.
-    - stylelint --config-basedir /var/www/.node/node_modules/
-      --config ${WEB_ROOT}/core/.stylelintrc.json -f verbose "${CSS_FILES}"
-    # - stylelint --config-basedir /var/www.node/node_modules/
-      # --config ${WEB_ROOT}/core/.stylelintrc.json -f verbose "${CSS_FILES}" > ${REPORT_DIR}/css-lint-report.txt
+    # Css report, terminal only for now.
+    - ${WEB_ROOT}/core/node_modules/.bin/stylelint
+        --config-basedir ${WEB_ROOT}/core/node_modules/
+        --config ${WEB_ROOT}/core/.stylelintrc.json
+        --formatter verbose "${CSS_FILES}"
 
 # This is a sass lint report, default rules used here for Bootstrap based sass.
 Sass lint:
@@ -499,13 +505,12 @@ Sass lint:
   before_script:
     - cp ${CI_PROJECT_DIR}/.gitlab-ci/RoboFile.php ${CI_PROJECT_DIR} || true
     - robo prepare:folders
-    - cd /var/www/.node/
-    - npm install --no-audit git://github.com/sasstools/sass-lint.git#develop
+    # Install stylelint from core/package.json
+    - robo yarn:install
+    - robo yarn add git://github.com/sasstools/sass-lint.git#develop
   script:
-    # Terminal result.
-    - /var/www/.node/node_modules/.bin/sass-lint --config ${SASS_CONFIG} --verbose --no-exit
     # Html report.
-    - /var/www/.node/node_modules/.bin/sass-lint --config ${SASS_CONFIG}
+    - ${WEB_ROOT}/core/node_modules/.bin/sass-lint --config ${SASS_CONFIG}
         --verbose
         --no-exit
         --format html
@@ -524,6 +529,7 @@ Sass lint:
   only:
     refs:
       - 8.x-dev
+      - master
       - tags
   except:
     variables:
@@ -547,7 +553,10 @@ Php metrics:
     paths:
       - ${REPORT_DIR}/
   script:
-    - phpqa ${PHPQA_REPORT} --tools phpmetrics ${PHPQA_PHP_CODE}
+    - phpqa
+        --buildDir ${REPORT_DIR}
+        --tools phpmetrics
+        --analyzedDirs ${PHP_CODE}
 
 # Phploc, Pdepend report, no pass or failure as it's just informative.
 Php stats:
@@ -558,7 +567,10 @@ Php stats:
       - $SKIP_METRICS == "1"
       - $SKIP_METRICS_PHPSTATS == "1"
   script:
-    - phpqa ${PHPQA_REPORT} --tools phploc,pdepend ${PHPQA_PHP_CODE}
+    - phpqa
+        --buildDir ${REPORT_DIR}
+        --tools phploc,pdepend
+        --analyzedDirs ${PHP_CODE}
 
 ################################################################################
 # [DEPLOY] Deploy jobs definition.
